# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Meisinger Two"
subtitle: "Soul Proprietor"
name: "Mike Meisinger"
description: "A friendly blog covering my journey through software development over the past twenty years"
baseurl: 
url: "https://meisinger.github.io"

# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

atom_feed:
  path:

twitter:
  username: "meisinger2"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meisinger2"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/meisinger"

author:
  name: "Mike Meisinger"
  avatar: "assets/images/avatar.png"
  bio: "A strongly opinionated introvert who writes code for a living."
  location: "Alpharetta, GA"
  email: "mike.meisinger@gmail.com"
  links: 
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meisinger2"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/meisinger"

remote_theme: "mmistakes/minimal-mistakes@4.19.0"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
