
title: "Meisinger Two"
subtitle: "Soul Proprietor"
name: "Mike Meisinger"
description: "A friendly blog covering my journey through software development over the past twenty years"
baseurl: 
url: "https://meisinger.github.io"

atom_feed:
  path:

twitter:
  username: "meisinger2"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meisinger2"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/meisinger"

author:
  name: "Mike Meisinger"
  avatar: "assets/images/avatar.png"
  bio: "A strongly opinionated introvert who writes code for a living."
  location: "Alpharetta, GA"
  email: "mike.meisinger@gmail.com"
  links: 
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meisinger2"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/meisinger"

remote_theme: "mmistakes/minimal-mistakes@4.19.0"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
